### ISSUE TITLE
[feature request] Display the name of the script

### ISSUE THREAD

**Issue by xfq** [w3c/type-samples#112]
The script tags are currently displayed in the FILTER BY SCRIPT section, but when I look for samples in a certain script or language, I often do not know what the script tag is, which is inconvenient. Is it possible to display the name of the script?

**Comment by xfq** [comment]
I have listed some scripts that we may use:

```json
{
  "adlm": "Adlam",
  "arab": "Arabic",
  "bali": "Balinese",
  "beng": "Bengali",
  "bopo": "Bopomofo",
  "cans": "Unified Canadian Aboriginal Syllabics",
  "cyrl": "Cyrillic",
  "deva": "Devanagari",
  "ethi": "Ethiopic",
  "geor": "Georgian",
  "grek": "Greek",
  "hang": "Hangul",
  "hani": "Han",
  "hebr": "Hebrew",
  "java": "Javanese",
  "jpan": "Japanese",
  "khmr": "Khmer",
  "laoo": "Lao",
  "latn": "Latin",
  "mlym": "Malayalam",
  "mong": "Mongolian",
  "nkoo": "N’Ko",
  "taml": "Tamil",
  "thai": "Thai",
  "tibt": "Tibetan"
}
```

**Comment by xfq** [comment]
Here is a more complete list, but the underscores in the script names should be replaced with spaces: https://github.com/r12a/app-subtags/blob/gh-pages/scriptcodes.js

**Comment by r12a** [comment]
fwiw, that's the _full_ list - there are no others.  It's kept up to date every time IANA issues an update.

**Comment by r12a** [comment]
Oops. That's not correct.  This list dates from 2014.  Let me check for an alternative...

**Comment by r12a** [comment]
The up to date file is https://github.com/r12a/app-subtags/blob/gh-pages/scripts.js

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/type-samples/commit/740644f7cd909ed146632c7a5d228624612895df
