### ISSUE TITLE
hebr he (proper) Hebrew Hyphen

### ISSUE THREAD

**Issue by Weigern** [w3c/type-samples#54]
Proper Hebrew hyphen is used in compounds, constructs and other cases in Hebrew.
Unlike a dash or a "minus" sign used for separation etc., a Hebrew hyphen is aligned with the top of the letters.
It is represented in Unicode ([https://www.fileformat.info/info/unicode/char/05be/index.htm](url)) but 
because it is not easily accessible, in current Hebrew usage a dash or "minus" sign are much more prevalent

![image](https://cloud.githubusercontent.com/assets/26392504/23875075/c8192bbc-0840-11e7-80e4-90f2b5cacc81.png)

![image](https://cloud.githubusercontent.com/assets/26392504/23875182/28c51f0c-0841-11e7-9078-543bf7e17652.png)

![image](https://cloud.githubusercontent.com/assets/26392504/23875305/a31a6f82-0841-11e7-932a-e4f2da7104ef.png)

**Comment by tomerm** [comment]
@Weigern very interesting :+1:  In case of third example it is pretty straightforward: "Municipality of Tel--Aviv". Hebrew hyphen is used to separate two parts of city name (Tel-Aviv which means in Hebrew literally Mound-Spring). For more on the etymology of this name please see: https://en.wikipedia.org/wiki/Tel_Aviv#Etymology_and_origins

It is far less clear why it is used in first two cases. For example middle example says: [And God said, "Let there be--light," and there was--light]. I replaced Hebrew hyphen with double minus sign in English translation. The hyphen is positioned between verb and noun. Do you have any idea for what purpose ? 

Additional interesting cases of Hebrew punctuation (including cantillation marks) can be found at: https://en.wikipedia.org/wiki/Hebrew_punctuation

**Comment by Weigern** [comment]
@tomerm I believe - as you mentioned at the bottom of your comment - that the in the 1st two cases the hyphen/"maqaf" is used as a cantillation mark

**Comment by r12a** [comment]
Gentlemen, this discussion of typographic feature belongs in https://github.com/w3c/hlreq/issues rather than here. I plan to move it there unless you object in the next 24 hours.

**Comment by tomerm** [comment]
@r12a makes sense. thx.
